### ISSUE TITLE
Notifications of new Comments

### ISSUE THREAD

**Issue by Vandread911** [nyaadevs/nyaa#172] opened 2017-05-23 18:24 UTC
HI,

Would it be possible to add in notifications of new comments posted on your torrents and on your torrents list page to display the amount of comments on your torrents in the table.

- Maybe a private message system aswell which would also needed to be added to the new notifications system

see sample image of comments displayed;
https://s23.postimg.org/co9iuu1mj/2017-05-23_20_23_38-_Vandread911_Nyaa.png

**Comment by CounterPillow** [comment] 2017-05-23 22:43
Duplicate of #167 I guess

**Comment by nathancyam** [comment] 2017-05-24 08:40
It might be possible, but since we pretty much use Elastic Search to get the torrent listing, we would need to come with ways to ensure comments are updated there appropriately. Alternatively, we can make the change where if you are on own user page, we let load from the DB instead.

**Comment by Vandread911** [comment] 2017-05-24 16:26
@nathancyam comments displayed in your profile page will be fine: https://nyaa.si/user/{username}

see image below

https://s23.postimg.org/co9iuu1mj/2017-05-23_20_23_38-_Vandread911_Nyaa.png

**Comment by sharkykh** [comment] 2017-05-27 18:54
@Vandread911 

> comments displayed in your profile page will be fine
> see image below
> https://s23.postimg.org/co9iuu1mj/2017-05-23_20_23_38-_Vandread911_Nyaa.png

This will soon be available on the site, in every torrent list
![image](https://cloud.githubusercontent.com/assets/10238474/26504015/9e63105e-424b-11e7-9e3a-1ecb5ec29259.png)

**Comment by Golumpa** [comment] 2017-08-04 03:03
Any update on a notification system like the old Nyaa had or even a different way of doing it?

It gets a bit tedious to find out which of my torrents has new comments and which are old ones I have already seen.

**Comment by TheAMM** [comment] 2017-08-04 09:08
@Golumpa #230

**Comment by Arylide** [comment] 2017-11-10 23:20
Use #167 for this

**Closed by Arylide** 2017-11-10 23:20 UTC
