### ISSUE TITLE
Unusual torrent rejected by site

### ISSUE THREAD

**Issue by ReimuHakurei** [nyaadevs/nyaa#248] opened 2017-06-07 08:47 UTC
A user in IRC encountered an error when trying to upload this torrent to our site: https://anidex.info/?page=torrent&id=48835

`Malformed torrent metadata (path part is empty)`

Here is a human-readable dump of the .torrent file:

https://i.shoov.in/1496824809.txt

Torrents usually have all of the files in multi-file torrents in a directory. This torrent has them all with a null parent directory, which is odd. uTorrent shows it as multiple separate files. From what someone in IRC said, qBitTorrent shows them all in a directory named '_'. 

We need to add a handler for this weird broken .torrent.

**Comment by ReimuHakurei** [comment] 2017-06-07 08:50
It is of note that this is similar to the BitComet non-standard thing of marking empty directories with a null file inside.

**Comment by TheAMM** [comment] 2017-06-07 10:36
Transmission does not want to open the file and I'd really like to lean on that.
If a `.torrent` won't work in a well-used client, then we should not support it. 

BitComet's null files for empty directories makes sense in the end and most clients seem to be fine with that, but as I haven't read *ruTorrent* specs/docs I have no idea what is the aim with an empty preceding path part.

**Comment by ReimuHakurei** [comment] 2017-06-07 15:16
Sure. If it's just broken we don't want to support it. 

But... It's odd that I haven't ever seen this before. 

My main concern is if it is some sort of newer convention that just not all clients yet support or something. In that case we would want to support it.

**Comment by TheAMM** [comment] 2017-06-07 15:23
I seriously doubt it's some new convention, it makes no sense.
I had a look at the ruTorrent's Torrent.php (and original rwTorrent) - I'm not much of a PHP dev, so I can't "see" it all, but I'd guess someone made a torrent with file paths like/starting with `Haikyuu!! S3 [BD 1080P x264 FLACx2]//whateverfile.mkv` (two `/`) ...or something.
I'm not sure where the fault is, but it is not (can't be!) by design.

**Comment by ReimuHakurei** [comment] 2017-06-07 15:25
Even though the torrent says rutorrent, the person claimed they used mktorrent, which makes zero sense.

**Comment by ReimuHakurei** [comment] 2017-06-07 15:27
Also, either way, we need a more friendly error message in cases like this.

**Comment by TheAMM** [comment] 2017-06-07 15:32
Ahaa, see the anidex page:
`Complete name : /data/Haikyuu!! S3 [BD 1080P x264 FLACx2]//[Shadow95] Haikyuu!! S3 - 07 [BD 1080P x264 FLACx2].mkv`
Called it!

I'm against changing the validator output (it needs to stay technical), however adding a link/direct explanation of the validator errors is fine.

**Comment by TheAMM** [comment] 2017-06-07 15:33
Also yeah closing this because people are simply using their tools wrong; nothing wrong with our validation (other than /upload not explaining what they need to look at to fix it).

**Closed by TheAMM** 2017-06-07 15:33 UTC
Labels: bug
