### ISSUE TITLE
Deleted torrents not actually deleted

### ISSUE THREAD

**Issue by toynbeeidea** [nyaadevs/nyaa#229] opened 2017-05-31 22:28 UTC
Since nyaa.si has refused to cooperate with regards to giving me control of any of my old torrents back, I instead chose to pursue another route:  I reported all of my old torrents with a note they they needed to be deleted in order for me to upload updated versions.  Well, they've been deleted, but when I go to upload the new version, I am told "That torrent already exists (#911617)".  If you look, you'll see that 911617 does not, in fact, exist.

**Comment by TheAMM** [comment] 2017-05-31 23:07
Cooperation means both sides work together. Have you visited the IRC channel yet?

We do not yet nuke the torrents from the database, because people can edit their torrent name and description. The only case for a delete is when a bad/malicious/irrelevant torrent is uploaded on the site. We don't want the same torrent with the hash be uploaded again, if it's been deleted once.

Get on the IRC and verify you are who you claim to be. We can't blindly accept people transferring torrents into their own name.

Duplicate of #39.

**Closed by TheAMM** 2017-05-31 23:07 UTC
