### ISSUE TITLE
No password reset funtcion

### ISSUE THREAD

**Issue by MarkJeronimus** [nyaadevs/nyaa#291] opened 2017-07-13 16:47 UTC
I can't log in, and I can't find a password reset/recover function. That's an issue.

(offtopic: I could log in in februari)

**Comment by CounterPillow** [comment] 2017-07-13 18:25
This site didn't even exist in February.

**Comment by sharkykh** [comment] 2017-07-13 18:28
@MarkJeronimus Are you confusing Nyaa.se (the original NyaaTorrents) with Nyaa.si (this site)?
If so, you need to open a new account.

**Comment by TheAMM** [comment] 2017-07-22 19:02
Although @MarkJeronimus may have confused .se and .si, issue is still valid - although a duplicate of #44.

**Closed by TheAMM** 2017-07-22 19:02 UTC
Labels: enhancement
