### ISSUE TITLE
Search filter I miss.

### ISSUE THREAD

**Issue by vrvly** [nyaadevs/nyaa#305] opened 2017-07-24 19:02 UTC
When searching for torrents, there is feature I miss a lot. Fltering by date from-up to, same with size(7-12GB choice as example) and maybe even more parameters. Think it was available in old one and I used it a lot. thx

**Comment by TheAMM** [comment] 2017-10-28 18:43
Duplicate of #109

**Closed by TheAMM** 2017-10-28 18:43 UTC
Labels: enhancement, search
