### ISSUE TITLE
Category selector outside of search box

### ISSUE THREAD

**Issue by bsandro** [nyaadevs/nyaa#261] opened 2017-06-11 11:14 UTC
Would be nice to have a category selector buttons or smth like the old Nyaa had - to filter now we have to use the (empty) search box which is not quite intuitive imho.

**Comment by sharkykh** [comment] 2017-06-11 11:30
Duplicate of #128
And it's already in the works #180

**Comment by TheAMM** [comment] 2017-06-11 16:18
Please search the issues first, we just had #260 (the previous issue!) closed for being a duplicate.

**Closed by TheAMM** 2017-06-11 16:18 UTC
Labels: duplicate
