### ISSUE TITLE
Would Like An Option To Set A Calander Date Range For Most Torrents Downloaded Sort Option.

### ISSUE THREAD

**Issue by Darkmatterx76** [nyaadevs/nyaa#394] opened 2017-10-28 17:41 UTC
Right now if you select to sort your torrents by number of downloads it sorts all torrents, even if they are quite old. This is still a useful feature but it would be very helpful if we were given the option to include a date range such as "From Sept 1 to Oct 28." The main reason I personally would like to see such a feature is that when a new season starts I like to see which shows seem to be popular (lots of downloads) and which ones people think are duds. The same thing could be added to all sort options but I think it would be most helpful for the "most downloaded" one.

Thanks

**Comment by TheAMM** [comment] 2017-10-28 18:49
Duplicate of #109
Read the prefill next time, and please don't title-case the entire subject.

**Closed by TheAMM** 2017-10-28 18:49 UTC
