### ISSUE TITLE
Add more options to torrents

### ISSUE THREAD

**Issue by egozi44** [nyaadevs/nyaa#244] opened 2017-06-05 14:50 UTC
1. users should have the option to delete their own torrents for whatever reason. (not that it going to help considering that you could probably find it again on other sites after it was uploaded but it still better than having no control over your own torrents on this site)

2. subscribe button to follow uploaders should be considered  (probably was already mentioned here though) as it was really helpful in old nyaa

**Comment by sharkykh** [comment] 2017-06-05 14:56
> 2. subscribe button to follow uploaders should never considered (probably was already mentioned here though) as it was really helpful in old nyaa

1. Go to user page: https://nyaa.si/user/HorribleSubs
2. Click RSS button on the nav-bar: https://nyaa.si/?page=rss&u=HorribleSubs
3. Use a RSS feed reader.
4. Voila

**Comment by egozi44** [comment] 2017-06-05 15:21
opps seem like my auto correct changed "be" to "never"

and I meant to normal subscribe button, I belive even the old cat realize that few people use RSS  over build in subscribe system

**Comment by TheAMM** [comment] 2017-06-05 15:25
>1. users should have the option to delete their own torrents for whatever reason. (not that it going to help considering that you could probably find it again on other sites after it was uploaded but it still better than having no control over your own torrents on this site)

Duplicate of #39.

For 2., maybe perhaps someday, but not now.

**Closed by TheAMM** 2017-06-05 15:25 UTC
Labels: duplicate, for-later-consideration

**Comment by egozi44** [comment] 2017-06-05 16:10
May I ask why?

nyaa v2  project meant you want to be better than nyaa v1 right?  how will you achieve it if you missing few of the basic options old nyaa had?


I also didn't got proper answer in regard to the subscribe question (yes/no/maybe)

just got alternative

**Comment by sharkykh** [comment] 2017-06-05 16:22
>I also didn't got proper answer in regard to the subscribe question (yes/no/maybe)
>
>just got alternative

You did,
> For 2., maybe perhaps someday, but not now.
