### ISSUE TITLE
a

### ISSUE THREAD

**Issue by ghost** [nyaadevs/nyaa#278] opened 2017-06-30 01:19 UTC
b

**Comment by sharkykh** [comment] 2017-06-30 04:12
#255

**Comment by mreweilk** [comment] 2017-07-04 05:19
This is sort of a duplicate of issue #255 and also any torrent downloaded from the site automatically has the new tracker added to it. 

Unless you're saying that we don't have the torrent file for this particular torrent?

**Closed** 2017-07-04 11:15 UTC
Labels: duplicate
