### ISSUE TITLE
Can't comment on a torrent when logged in.

### ISSUE THREAD

**Issue by MaximeMorin** [nyaadevs/nyaa#442] opened 2018-02-01 18:02 UTC
I can't comment on torrents, even when I'm logged in.  I can't figure out why.  

Here's an example:
![nyaa](https://user-images.githubusercontent.com/5142935/35694598-cf169526-074f-11e8-9318-af888b944ca8.JPG)

It seems that the comment box is not rendered in the HTML when I view torrents.

![image](https://user-images.githubusercontent.com/5142935/35694702-165b1b6e-0750-11e8-9881-9eb6313808b3.png)

I'm using Chrome (standard, not in incognito mode)

**Comment by ReimuHakurei** [comment] 2018-02-01 18:21
Commenting is disabled for accounts less than one week old to prevent spam.

On Feb 1, 2018 12:02 PM, "Maxime Morin" <notifications@github.com> wrote:

I can't comment on torrents, even when I'm logged in. I can't figure out
why.

Here's an example:
[image: nyaa]
<https://user-images.githubusercontent.com/5142935/35694598-cf169526-074f-11e8-9318-af888b944ca8.JPG>

It seems that the comment box is not rendered in the HTML when I view
torrents.

[image: image]
<https://user-images.githubusercontent.com/5142935/35694702-165b1b6e-0750-11e8-9881-9eb6313808b3.png>

I'm using Chrome (standard, not in incognito mode)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nyaadevs/nyaa/issues/442>, or mute the thread

**Comment by CounterPillow** [comment] 2018-02-01 18:34
Working as intended, will get changed to just showing a CAPTCHA once https://github.com/nyaadevs/nyaa/pull/439 gets merged.

**Closed by CounterPillow** 2018-02-01 18:34 UTC

**Comment by MaximeMorin** [comment] 2018-02-02 00:44
Ah, that makes sense, thanks!
